--Drop All
DROP TABLE ORDER_CONTENT;
DROP TABLE SUPPLIER;
DROP TABLE PRODUCT;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE PARCEL;
DROP TABLE CUST_ORDER;
DROP TABLE PAYMENT;
DROP TABLE CUST_ADDRESS;
DROP TABLE SUPPORT_TICKET;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_TYPE;
DROP TABLE CUSTOMER;

DROP SEQUENCE "Cust_ID_SEQ";
DROP SEQUENCE "Emp_Type_ID_SEQ";
DROP SEQUENCE "Emp_ID_SEQ";
DROP SEQUENCE "Tic_ID_SEQ";
DROP SEQUENCE "Pay_ID_SEQ";
DROP SEQUENCE "Order_ID_SEQ";
DROP SEQUENCE "Par_ID_SEQ";
DROP SEQUENCE "Category_ID_SEQ";
DROP SEQUENCE "Product_ID_SEQ";
DROP SEQUENCE "Supplier_ID_SEQ";

DROP VIEW "OPEN_UNNASIGNED_TICKETS";
DROP VIEW "MANAGERS";
DROP VIEW "COMPLETED_PAYMENTS";
DROP VIEW "Customer_Service";