INSERT INSERT CUSTOMER (Cust_ID, Cust_FName, Cust_SName, Cust_Email, Cust_Phone) VALUES (63, 'Blondie', 'Mallabar', 'bmallabar1q@comsenz.com', '+2794691873');
INSERT INSERT EMPLOYEE_TYPE (Emp_Type_ID, Emp_Type_Description) VALUES (1, 'Customer Service');
INSERT INSERT EMPLOYEE (Emp_ID, Emp_Name, Emp_Date, Emp_Standard_Rate, Emp_Overtime_Rate, Emp_Weekly_Hours, Emp_Manager_ID, Emp_Type_ID) VALUES (29, 'Sloan', '08-Jun-2021', 29.88, 37.85, 40, NULL, 1);
INSERT INSERT SUPPORT_TICKET (Tic_ID, Tic_Date, Tic_Status, Emp_ID, Cust_ID) VALUES (14, '12-Apr-2022', 'Open', 20, 72);
INSERT INSERT CUST_ADDRESS (Cust_ID, Add_City, Add_Street, Add_StreetNr, Add_Suburb, Add_Province) VALUES (22, 'Kimberly', 'Lien', '7', 7404, 'Western Cape');
INSERT INSERT PAYMENT (Pay_ID, Pay_Ammount, Pay_Status, Cust_ID) VALUES (35, 1207.69, 'Cancelled', 68);
INSERT INSERT CUST_ORDER (Order_ID, Order_Type, Pay_Confimed, Pay_Date, Order_Total, Pay_ID) VALUES (26, 'Supplier', 'Confirmed', '8/31/2021', 3259.1, 36);
INSERT INSERT PARCEL (Par_ID, Par_Date, Par_TrackingNo, Order_ID) VALUES (64, '26-Aug-2021', 'BN76338107', 24);
INSERT INSERT PRODUCT_CATEGORY (Category_ID, Category_Name) VALUES (6, 'Electronics');
INSERT INSERT PRODUCT (Product_ID, Product_Name, Product_Weight, Product_Price, Product_Quantity, Category_ID) VALUES (27, 'Wine - Cave Springs Dry Riesling', 2.9, 1282.32, 2, 9);
INSERT INSERT SUPPLIER (Supplier_ID, Order_Date, Product_ID) VALUES (33, 'Mushroom - Chantrelle, Fresh', 66);
INSERT INSERT ORDER_CONTENT (Order_ID, Product_ID) VALUES (89, 6);