--Drop tables (Not in correct order)
DROP TABLE PRODUCT;
DROP TABLE SUPPLIER;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE PAYMENT;
DROP TABLE PARCEL;
DROP TABLE CUST_ORDER;
DROP TABLE SUPPORT_TICKET;
DROP TABLE CUST_ADDRESS;
DROP TABLE ORDER_CONTENT;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_TYPE;
DROP TABLE CUSTOMER;