--Drop All
DROP TABLE ORDER_CONTENT CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PARCEL CASCADE CONSTRAINTS;
DROP TABLE CUST_ORDER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE CUST_ADDRESS CASCADE CONSTRAINTS;
DROP TABLE SUPPORT_TICKET CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_TYPE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

DROP SEQUENCE Cust_ID_SEQ;
DROP SEQUENCE Emp_Type_ID_SEQ;
DROP SEQUENCE Emp_ID_SEQ;
DROP SEQUENCE Tic_ID_SEQ;
DROP SEQUENCE Pay_ID_SEQ;
DROP SEQUENCE Order_ID_SEQ;
DROP SEQUENCE Par_ID_SEQ;
DROP SEQUENCE Category_ID_SEQ;
DROP SEQUENCE Product_ID_SEQ;
DROP SEQUENCE Supplier_ID_SEQ;