CREATE OR REPLACE VIEW Open_Unnasigned_Tickets AS
SELECT * FROM SUPPORT_TICKET
WHERE Emp_ID IS NULL AND Tic_Status = 'Open';

CREATE OR REPLACE VIEW MANAGERS AS
SELECT Emp_ID, Emp_Name FROM EMPLOYEE
WHERE Emp_Manager_ID IS NOT NULL;

CREATE OR REPLACE VIEW COMPLETED_PAYMENTS AS
SELECT * FROM PAYMENT
WHERE Pay_Status = 'Complete';

CREATE OR REPLACE VIEW  AS Customer_Service
SELECT EMPLOYEE.Emp_Name FROM EMPLOYEE, EMPLOYEE_TYPE
WHERE EMPLOYEE_TYPE.Emp_Type_Description = 'Customer Service';