CREATE OR REPLACE VIEW Open_Unnasigned_Tickets AS
SELECT * FROM SUPPORT_TICKET
WHERE Emp_ID IS NULL AND Tic_Status = 'Open';

CREATE OR REPLACE VIEW MANAGERS AS
SELECT Emp_ID, Emp_Name FROM EMPLOYEE
WHERE Emp_Manager_ID IS NOT NULL;

CREATE OR REPLACE VIEW COMPLETED_PAYMENTS AS
SELECT * FROM PAYMENT
WHERE Pay_Status = 'Confirmed';

CREATE OR REPLACE VIEW Customer_Service AS
SELECT Emp_Name FROM EMPLOYEE
WHERE Emp_Type_ID = 1;